// @ts-check
// SPDX-License-Identifier: MIT
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
//
// `site` is the canonical URL the build uses for absolute links
// (sitemap, OpenGraph, canonical tags, JSON-LD). Update this if you
// fork the project and host elsewhere. The live site runs at
// https://open-apps.dev.mn.
//
// The sitemap itself is generated by a custom Astro endpoint at
// `src/pages/sitemap.xml.ts` rather than `@astrojs/sitemap`, so the
// public URL is exactly `/sitemap.xml` (no `-index.xml` suffix).
export default defineConfig({
  site: 'https://open-apps.dev.mn',
  trailingSlash: 'ignore',
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    format: 'directory',
  },
});
