export type Contributor = {
  username: string;
  name?: string;
  avatarUrl: string;
  profileUrl: string;
  contributions?: number;
};

// V1 static list. Will be generated by a GitHub Action in V2 from
// `GET /repos/{owner}/{repo}/contributors`. All contributors visible
// on the homepage — no "and more" truncation.
export const contributors: Contributor[] = [
  { username: "tortuvshin", name: "Turtuvshin Byambaa", avatarUrl: "https://avatars.githubusercontent.com/u/9253889?v=4", profileUrl: "https://github.com/tortuvshin", contributions: 120 },
  { username: "imranr98", name: "Imran R", avatarUrl: "https://avatars.githubusercontent.com/u/26409776?v=4", profileUrl: "https://github.com/ImranR98", contributions: 87 },
  { username: "mitesh77", name: "Mitesh Patel", avatarUrl: "https://avatars.githubusercontent.com/u/31113970?v=4", profileUrl: "https://github.com/mitesh77", contributions: 64 },
  { username: "x-wei", name: "X-Wei", avatarUrl: "https://avatars.githubusercontent.com/u/1212301?v=4", profileUrl: "https://github.com/X-Wei", contributions: 58 },
  { username: "localsend", name: "LocalSend", avatarUrl: "https://avatars.githubusercontent.com/u/109984596?v=4", profileUrl: "https://github.com/localsend", contributions: 41 },
  { username: "fbernaly", name: "Freddy Bernal", avatarUrl: "https://avatars.githubusercontent.com/u/12874469?v=4", profileUrl: "https://github.com/fbernaly", contributions: 37 },
  { username: "yongjhih", name: "Andrew Chen", avatarUrl: "https://avatars.githubusercontent.com/u/2137368?v=4", profileUrl: "https://github.com/yongjhih", contributions: 35 },
  { username: "pawar141", name: "Pawan Kumar", avatarUrl: "https://avatars.githubusercontent.com/u/19870668?v=4", profileUrl: "https://github.com/pawar141", contributions: 33 },
  { username: "codetricity", name: "Codetricity", avatarUrl: "https://avatars.githubusercontent.com/u/3541585?v=4", profileUrl: "https://github.com/codetricity", contributions: 29 },
  { username: "kk-mark", name: "Karthik K", avatarUrl: "https://avatars.githubusercontent.com/u/4020044?v=4", profileUrl: "https://github.com/kk-mark", contributions: 27 },
  { username: "hdevalence", name: "Henry de Valence", avatarUrl: "https://avatars.githubusercontent.com/u/82609?v=4", profileUrl: "https://github.com/hdevalence", contributions: 25 },
  { username: "shmsi", name: "Syed Muhammad Ali", avatarUrl: "https://avatars.githubusercontent.com/u/12603011?v=4", profileUrl: "https://github.com/shmsi", contributions: 24 },
  { username: "ptsiakos", name: "P. Tsiakos", avatarUrl: "https://avatars.githubusercontent.com/u/10936605?v=4", profileUrl: "https://github.com/ptsiakos", contributions: 22 },
  { username: "amugofjava", name: "amugofjava", avatarUrl: "https://avatars.githubusercontent.com/u/12624365?v=4", profileUrl: "https://github.com/amugofjava", contributions: 21 },
  { username: "wbrawner", name: "Billy Brawner", avatarUrl: "https://avatars.githubusercontent.com/u/10061852?v=4", profileUrl: "https://github.com/wbrawner", contributions: 19 },
  { username: "csonuryilmaz", name: "C. Sonur Yilmaz", avatarUrl: "https://avatars.githubusercontent.com/u/4230828?v=4", profileUrl: "https://github.com/csonuryilmaz", contributions: 18 },
  { username: "dahlia-os", name: "Dahlia OS", avatarUrl: "https://avatars.githubusercontent.com/u/52172515?v=4", profileUrl: "https://github.com/dahlia-os", contributions: 17 },
  { username: "shabbirdwd53", name: "Shabbir D", avatarUrl: "https://avatars.githubusercontent.com/u/27217528?v=4", profileUrl: "https://github.com/shabbirdwd53", contributions: 16 },
  { username: "mahmudahsan", name: "Mahmud Ahsan", avatarUrl: "https://avatars.githubusercontent.com/u/10694477?v=4", profileUrl: "https://github.com/mahmudahsan", contributions: 15 },
  { username: "maciekish", name: "Maciej B", avatarUrl: "https://avatars.githubusercontent.com/u/407450?v=4", profileUrl: "https://github.com/maciekish", contributions: 14 },
  { username: "gskinnerTeam", name: "gskinner", avatarUrl: "https://avatars.githubusercontent.com/u/309497?v=4", profileUrl: "https://github.com/gskinnerTeam", contributions: 13 },
  { username: "rahulsharmavv", name: "Rahul Sharma", avatarUrl: "https://avatars.githubusercontent.com/u/42631883?v=4", profileUrl: "https://github.com/rahulsharmavv", contributions: 12 },
  { username: "kharioki", name: "Kharioki", avatarUrl: "https://avatars.githubusercontent.com/u/53388854?v=4", profileUrl: "https://github.com/kharioki", contributions: 12 },
  { username: "suyashbhatt", name: "Suyash Bhatt", avatarUrl: "https://avatars.githubusercontent.com/u/19732431?v=4", profileUrl: "https://github.com/suyashbhatt", contributions: 11 },
  { username: "londonro", name: "London Roberts", avatarUrl: "https://avatars.githubusercontent.com/u/12028176?v=4", profileUrl: "https://github.com/londonro", contributions: 11 },
  { username: "bramvbilsen", name: "Bram Van Bilsen", avatarUrl: "https://avatars.githubusercontent.com/u/16198555?v=4", profileUrl: "https://github.com/bramvbilsen", contributions: 10 },
  { username: "tekulvw", name: "tekulvw", avatarUrl: "https://avatars.githubusercontent.com/u/4037029?v=4", profileUrl: "https://github.com/tekulvw", contributions: 10 },
  { username: "renefloor", name: "René Floor", avatarUrl: "https://avatars.githubusercontent.com/u/18149872?v=4", profileUrl: "https://github.com/renefloor", contributions: 9 },
  { username: "nfrankel", name: "Nicolas Frankel", avatarUrl: "https://avatars.githubusercontent.com/u/1922587?v=4", profileUrl: "https://github.com/nfrankel", contributions: 9 },
  { username: "ppiekarczyk", name: "Piotr Piekarczyk", avatarUrl: "https://avatars.githubusercontent.com/u/1470239?v=4", profileUrl: "https://github.com/ppiekarczyk", contributions: 8 },
  { username: "haarts", name: "Harmen A.", avatarUrl: "https://avatars.githubusercontent.com/u/32027?v=4", profileUrl: "https://github.com/haarts", contributions: 8 },
  { username: "itinance", name: "itinance", avatarUrl: "https://avatars.githubusercontent.com/u/2616392?v=4", profileUrl: "https://github.com/itinance", contributions: 7 },
  { username: "nils-rek", name: "nils-rek", avatarUrl: "https://avatars.githubusercontent.com/u/21639318?v=4", profileUrl: "https://github.com/nils-rek", contributions: 7 },
  { username: "vallentin", name: "Christian Vallentin", avatarUrl: "https://avatars.githubusercontent.com/u/17458817?v=4", profileUrl: "https://github.com/vallentin", contributions: 6 },
  { username: "Tugbayatilla", name: "Tuğbay Atilla", avatarUrl: "https://avatars.githubusercontent.com/u/19685084?v=4", profileUrl: "https://github.com/Tugbayatilla", contributions: 6 },
  { username: "rrousselGit", name: "Remi Rousselet", avatarUrl: "https://avatars.githubusercontent.com/u/1401447?v=4", profileUrl: "https://github.com/rrousselGit", contributions: 6 },
  { username: "fluttertutorial", name: "Flutter Tutorial", avatarUrl: "https://avatars.githubusercontent.com/u/10893602?v=4", profileUrl: "https://github.com/fluttertutorial", contributions: 5 },
  { username: "Gustl22", name: "Gustav L.", avatarUrl: "https://avatars.githubusercontent.com/u/18216829?v=4", profileUrl: "https://github.com/Gustl22", contributions: 5 },
  { username: "lukasgit", name: "lukasgit", avatarUrl: "https://avatars.githubusercontent.com/u/6640103?v=4", profileUrl: "https://github.com/lukasgit", contributions: 5 },
  { username: "miquelbeltran", name: "Miquel Beltran", avatarUrl: "https://avatars.githubusercontent.com/u/2490387?v=4", profileUrl: "https://github.com/miquelbeltran", contributions: 5 },
  { username: "tomwong", name: "Tom Wong", avatarUrl: "https://avatars.githubusercontent.com/u/13203235?v=4", profileUrl: "https://github.com/tomwong", contributions: 4 },
  { username: "rIIh", name: "rIIh", avatarUrl: "https://avatars.githubusercontent.com/u/20112511?v=4", profileUrl: "https://github.com/rIIh", contributions: 4 },
  { username: "ueman", name: "ueman", avatarUrl: "https://avatars.githubusercontent.com/u/18186937?v=4", profileUrl: "https://github.com/ueman", contributions: 4 },
  { username: "kevmoo", name: "Kevin Moore", avatarUrl: "https://avatars.githubusercontent.com/u/170335?v=4", profileUrl: "https://github.com/kevmoo", contributions: 4 },
  { username: "eseidel", name: "Erik Seidel", avatarUrl: "https://avatars.githubusercontent.com/u/249302?v=4", profileUrl: "https://github.com/eseidel", contributions: 3 },
  { username: "RK-GitHub-Account", name: "RK", avatarUrl: "https://avatars.githubusercontent.com/u/33702230?v=4", profileUrl: "https://github.com/RK-GitHub-Account", contributions: 3 },
  { username: "MarcusNg", name: "Marcus Ng", avatarUrl: "https://avatars.githubusercontent.com/u/42465749?v=4", profileUrl: "https://github.com/MarcusNg", contributions: 3 },
];
